/*
 Navicat Premium Data Transfer

 Source Server         : localhost_oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 03/07/2020 09:15:00
*/


-- ----------------------------
-- Table structure for DEPARTMENTS
-- ----------------------------
DROP TABLE "SCOTT"."DEPARTMENTS";
CREATE TABLE "SCOTT"."DEPARTMENTS" (
  "DEPARTMENT_ID" NUMBER(4,0) NOT NULL,
  "DEPARTMENT_NAME" VARCHAR2(30 BYTE) NOT NULL,
  "MANAGER_ID" NUMBER(6,0),
  "LOCATION_ID" NUMBER(4,0)
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DEPARTMENTS
-- ----------------------------
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('10', 'Administration', '200', '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('20', 'Marketing', '201', '1800');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('30', 'Purchasing', '114', '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('40', 'Human Resources', '203', '2400');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('50', 'Shipping', '121', '1500');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('60', 'IT', '103', '1400');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('70', 'Public Relations', '204', '2700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('80', 'Sales', '145', '2500');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('90', 'Executive', '100', '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('100', 'Finance', '108', '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('110', 'Accounting', '205', '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('120', 'Treasury', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('130', 'Corporate Tax', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('140', 'Control And Credit', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('150', 'Shareholder Services', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('160', 'Benefits', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('170', 'Manufacturing', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('180', 'Construction', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('190', 'Contracting', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('200', 'Operations', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('210', 'IT Support', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('220', 'NOC', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('230', 'IT Helpdesk', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('240', 'Government Sales', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('250', 'Retail Sales', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('260', 'Recruiting', NULL, '1700');
INSERT INTO "SCOTT"."DEPARTMENTS" VALUES ('270', 'Payroll', NULL, '1700');

-- ----------------------------
-- Primary Key structure for table DEPARTMENTS
-- ----------------------------
ALTER TABLE "SCOTT"."DEPARTMENTS" ADD CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID");

-- ----------------------------
-- Checks structure for table DEPARTMENTS
-- ----------------------------
ALTER TABLE "SCOTT"."DEPARTMENTS" ADD CONSTRAINT "DEPT_NAME_NN" CHECK ("DEPARTMENT_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table DEPARTMENTS
-- ----------------------------
ALTER TABLE "SCOTT"."DEPARTMENTS" ADD CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID") REFERENCES "SCOTT"."LOCATIONS" ("LOCATION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."DEPARTMENTS" ADD CONSTRAINT "DEPT_MGR_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "SCOTT"."EMPLOYEES" ("EMPLOYEE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
